name: iroha_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  hotreloader: ^3.0.6
  logging: ^1.1.1
  path: ^1.8.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  analyzer: ^5.11.1
  args: ^2.4.1
  intl: ^0.18.1
  lints: ^2.0.0
  test: ^1.24.2
